export interface Company{
    
    id:number,
    firstName:string,
    middleName: string,
    lastName:string,
    name:string,
    tradeName:string,
    birthdate: Date,
    gender:string,
    address:string,
    zipCode:string,
    contact:string,
    tin:string,
    rdo:string,
    occupation:string,
    deductionMethod:string,
    businessType:string,
    incomeSource:string,
    cor:string,
    dateCreated: Date,
    email:string,
    forms:string,
    taxpayerType:string,
    taxCode:string,
    incomeTaxRateType:string,
    signature:string,
    birRegistration:Date,
    civilStatus:string,
    citizenship:string,
    spouseHasIncome:boolean,
    incomeTaxExempt:boolean,
    specialRate:boolean,
    bmbe:boolean,
    usage:string,
    isCorporation:boolean,
    isDormant:boolean,
    dataSource:string,
    planName: string,
    dateExpired: Date,
    card: number,
    cycleType: string,
    status: number,
    cycleDateCreated: Date,
    paymentId: number
}